# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_EteHL3xoKOApjOXrmbM6AcJ7kVzXkoT
"""

import yfinance as yf
from sklearn.linear_model import LinearRegression
import numpy as np

# Download data
data = yf.download('AAPL', period='100d')
close_prices = data['Close'].values

# Prepare data
X = close_prices[:-1].reshape(-1, 1)
y = close_prices[1:]

# Train model
model = LinearRegression()
model.fit(X, y)

# Predict tomorrow’s price
latest_price = close_prices[-1]
predicted_price = model.predict(np.array([[latest_price]]).reshape(1, -1))[0]

# Print result
print(f"Predicted closing price is: ${float(predicted_price):.2f}")